//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStar
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int AccountID { get; set; }
        public Nullable<int> AccountTypeID { get; set; }
        public Nullable<int> AccountPermissionID { get; set; }
        public string AccountName { get; set; }
    
        public virtual AccountType AccountType { get; set; }
        public virtual AccountPermission AccountPermission { get; set; }
    }
}
