//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStar
{
    using System;
    using System.Collections.Generic;
    
    public partial class System
    {
        public int SystemID { get; set; }
        public string SystemName { get; set; }
        public string SystemCategory { get; set; }
    }
}
